In [1]:
print("Random samples")

Random samples

In [2]:
import pandas as pd
Favmovie={
    "movie":["RRR","WAR",3],
}
result=pd.DataFrame(Favmovie)
print(result)

  movie
0   RRR
1   WAR
2     3

In [3]:
import pandas as pd
Favmovie={
    "movie":["eega","i","nani"]
}
result=pd.DataFrame(Favmovie)
result.sample(1)
result.sample(2)

  movie
2  nani
0  eega

In [6]:
import pandas as pd
Favsubject={
    "subject":["mathematics","physics","science"]
               }
result=pd.DataFrame(Favsubject)
result.sample(2,random_state=0)

   subject
2  science
1  physics

In [22]:
date= {

"Data":["2012-03-2","2023-09-3","2019-09-4"]
}
result=pd.DataFrame(date)
result["date"]=pd. to_datetime(result["Data"])
print(result)

        Data       date
0  2012-03-2 2012-03-02
1  2023-09-3 2023-09-03
2  2019-09-4 2019-09-04

In [30]:
date= {
    "Data":["2015-04-6","2017-09-7","2016-05-9"]
}

result=pd.DataFrame(date)
result["date"]=pd.to_datetime(result["Data"])
result["date"].dt. time

0    00:00:00
1    00:00:00
2    00:00:00
Name: date, dtype: object

In [33]:
from datetime import datetime
date1= datetime(2025,3,20)
date2= datetime(2024,4,15)
print(date2-date1)

-339 days, 0:00:00

In [34]:
import pandas as pd
data = pd.Series(range(1,100))
sample=data.sample(5)
print(sample)

31    32
40    41
65    66
12    13
81    82
dtype: int64

In [35]:
import pandas as pd
data=pd.Series(range(1,100))
sample=data.sample(frac=0.2)
print(sample)

86    87
33    34
94    95
93    94
14    15
91    92
52    53
22    23
59    60
37    38
88    89
66    67
61    62
76    77
65    66
71    72
67    68
26    27
1      2
3      4
dtype: int64

In [38]:
import numpy as np
salary=([2000,3000,4000,5000])
print(np.mean(salary))

3500.0

In [40]:
import numpy as np
salary=([25,34,78,67])
print(np.median(salary))

50.5